-- Insert pages
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES
(1, NOW(), NOW(), '<h2>Войсковой собор святого благоверного князя Александра Невского</h2><p><strong>Адрес:</strong><br>Местная религиозная организация православный приход войскового собора святого благоверного князя Александра Невского<br>Юридический адрес: 350063, Россия, г. Краснодар, ул. Красная, д. 1<br>Фактический адрес: 350063, Россия, г. Краснодар, ул. Постовая, д. 26</p><p><strong>Телефон:</strong><br>(861) 262-00-20<br>8-918-315-94-13 (настоятель Собора протоиерей Иоанн Гармаш)<br>8-953-080-76-72 (киоск, 07:00-19:00)</p><p><strong>E-mail:</strong> nevskiy-sobor@mail.ru</p><p><strong>Группа ВКОНТАКТЕ:</strong> <a href=\"https://vk.com/voyskovoysoborkrasnodar\">https://vk.com/voyskovoysoborkrasnodar</a></p><p><strong>Телеграмм-канал:</strong> <a href=\"https://t.me/alexnewsobor\">https://t.me/alexnewsobor</a></p><p><strong>Проезд:</strong><br>Трамвай: 2, 4 – до ост. Городской сад<br>Троллейбус: 7, 12, 20 – до ост. ул. Советская; 9, 10 – до ост. ул. Постовая<br>Маршрутное такси: 3, 19Б (49), 26А, 44</p>', 'Контакты', '', 'publish', 'closed', 'closed', '', 'kontakty', '', '', NOW(), NOW(), '', 0, '', 0, 'page', '', 0),
(1, NOW(), NOW(), '<h2>Расписание богослужений</h2><p>Воскресенье:<br>Ранняя Литургия: 7:00<br>Поздняя Литургия: 10:00</p><p>Будние дни:<br>Вечерня: 17:00<br>Утреня: 6:00<br>Литургия: 7:00</p><p>Суббота:<br>Всенощное бдение: 17:00</p>', 'Расписание богослужений', '', 'publish', 'closed', 'closed', '', 'raspisanie-bogosluzhenij', '', '', NOW(), NOW(), '', 0, '', 0, 'page', '', 0),
(1, NOW(), NOW(), '<h2>Духовенство собора</h2><h3>Настоятель собора протоиерей Иоанн Гармаш</h3><p>Гармаш Иван Васильевич родился 8 февраля 1965 г. в х. Плавни Крымского района Краснодарского края.</p><h3>Иерей Вячеслав Феер</h3><p>Дата рождения: 17 апреля 1989 г.</p><h3>Иерей Александр Клочков</h3><p>Образование: Николо-Угрешская Духовная Семинария, Московская Духовная Академия.</p><h3>Иерей Олег Попов</h3><p>Образование: КубГАУ.</p><h3>Протодиакон Максим Кадуров</h3><p>Дата рождения: 18.04.1982.</p>', 'Духовенство собора', '', 'publish', 'closed', 'closed', '', 'duhovenstvo-sobora', '', '', NOW(), NOW(), '', 0, '', 0, 'page', '', 0);

-- Insert posts
INSERT INTO wp_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES
(1, NOW(), NOW(), 'В воскресенье после поздней литургии прошёл разговор с отцом Александром. Говорили о воскресном евангельском чтении и житии преподобной Марии Египетской.', 'Разговор после поздней литургии', '', 'publish', 'open', 'open', '', 'razgovor-posle-pozdnej-liturgii', '', '', NOW(), NOW(), '', 0, '', 0, 'post', '', 0),
(1, NOW(), NOW(), 'После Божественной литургии молодёжный хор собрался на репетицию.', 'Воскресное пение в радость Господу', '', 'publish', 'open', 'open', '', 'voskresnoe-penie-v-radost-gospodu', '', '', NOW(), NOW(), '', 0, '', 0, 'post', '', 0);

-- Insert category
INSERT INTO wp_terms (name, slug, term_group) VALUES ('Новости', 'novosti', 0);
INSERT INTO wp_term_taxonomy (term_id, taxonomy, description, parent, count) VALUES (LAST_INSERT_ID(), 'category', '', 0, 2);

-- Link posts to category
INSERT INTO wp_term_relationships (object_id, term_taxonomy_id, term_order) VALUES
((SELECT ID FROM wp_posts WHERE post_title = 'Разговор после поздней литургии'), (SELECT term_taxonomy_id FROM wp_term_taxonomy WHERE term_id = LAST_INSERT_ID()), 0),
((SELECT ID FROM wp_posts WHERE post_title = 'Воскресное пение в радость Господу'), (SELECT term_taxonomy_id FROM wp_term_taxonomy WHERE term_id = LAST_INSERT_ID()), 0);